### ISSUE TITLE
Report a security vulnerability

### ISSUE THREAD

**Issue by JLLeitschuh** [streamr-dev/engine-and-editor#664]
Hi,
1. Can you create a GitHub security advisory so I can report a vulnerability? https://github.com/streamr-dev/engine-and-editor/security/advisories
2. I recommend adding a security policy to your GitHub organization under a `.github` repository. More information here: https://github.com/streamr-dev/engine-and-editor/security/policy

**Comment by hpihkala** [comment]
Thanks @JLLeitschuh for the suggestions! We'll set them up shortly. Right now the team is extremely busy with the upcoming network milestone launch, so please expect it to happen only after a couple of weeks from now. In the meanwhile, if you'd like to report a vulnerability, please get in touch via email to contact at streamr dot com.

**Comment by JLLeitschuh** [comment]
@hpihkala My standard disclosure is this:

> ## Responsible Disclosure Policy
>
> **This responsible disclosure follows Google's [90-day vulnerability disclosure policy](https://www.google.com/about/appsecurity/) (I'm not an employee of Google, I just like their policy). Full disclosure will occur either at the end of the 90-day deadline or whenever a patch is made widely available, whichever occurs first.**

I'll send you an email shortly.

**Comment by JLLeitschuh** [comment]
The email has been sent.
