### ISSUE TITLE
API Endpoint /products has empty streams array

### ISSUE THREAD

**Issue by sergejmueller** [streamr-dev/engine-and-editor#917]
**Current result**
The API call to [/products](https://www.streamr.com/api/v1/products?publicAccess=true) returns products, but the `streams` array of each product item is always empty. The API Explorer says, the streams array should contain stream IDs.

**Expected result**
API Endpoint `/products` returns stream IDs contained in the product.

**Comment by kare** [comment]
@sergejmueller Thanks for the report. We're investigating the issue.

**Comment by hpihkala** [comment]
Ha, nice catch! The `streams` field shouldn't actually be there at all (the docs are wrong in this case). It's some old remnant. 

Including the streams in the `/products` list makes the response big and heavy in case there are a lot of streams in the returned product(s). The streams for a product can be fetched easily enough via `/​products/${​id}/​streams`, so probably better not to have them in the product list endpoint.

So heads up, the useless empty `streams` array will go away! :)

**Comment by sergejmueller** [comment]
Thanks, @hpihkala
